server:
  port: ${server_port:9090}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}

zuul: 
  prefix: /api
  sensitive-headers: Cookie,Set-Cookie
#  Uncomment to disable services automatically registering in Zuul
#  ignoredServices: '*'

#  routes:
#    authen-service:
#      path: /api/**
#      url: http://authentication-service:8080

  
spring:
  application:
    name: zuul-server
    
    
management:
  security:
    enabled: false

  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  